# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
use_frameworks!

target 'Vac' do
    pod 'SwiftyJSON', '~> 2.2.0'
    pod 'RealmSwift'
    pod 'DOFavoriteButton'
end
